name: create pr from fork

on:
  repository_dispatch:
    types: [create_pr]

jobs:
  create_pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Add downstream
        run: git remote add hj https://github.com/hjenryin/testrepo.git
      - name: Fetch
        run: git fetch hj
      - name: Create pr
        - run: git checkout hj/new_test; gh pr create --title "t" --body "content" --repo alafumee/testrepo
          env:
            GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}